import os

# YOU CAN EITHER FILL THESE VARIABLES OUT HERE OR SET THEM IN YOUR ENVIRONMENT VARIABLE
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AMAZON_ASSOC_TAG=""

ENV = os.environ
AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID if AWS_ACCESS_KEY_ID else ENV.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY if AWS_SECRET_ACCESS_KEY else ENV.get("AWS_SECRET_ACCESS_KEY")
AMAZON_ASSOC_TAG = AMAZON_ASSOC_TAG if AMAZON_ASSOC_TAG else ENV.get("AMAZON_ASSOC_TAG")

assert AWS_ACCESS_KEY_ID, "AWS_ACCESS_KEY_ID not defined in config.py or environment"
assert AWS_SECRET_ACCESS_KEY, "AWS_SECRET_ACCESS_KEY not defined in config.py or env"
assert AMAZON_ASSOC_TAG, "AMAZON_ASSOC_TAG not defined in config.py or env"
